# set pretrained as a file path or an url, vision model, text model
pretrained: ''
vision_model_path: 'facebook/dinov2-giant'
lm_path: 't5-large'

# logging
wandb_team: 'harsh172'
wandb_project: 'image-captioning'

batch_size: 12
init_lr: 0.0001

image_size: 384

# generation configs
max_length: 25  
min_length: 5
num_beams: 3
prompt: ''

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10
