image_root: '/export/share/datasets/vision/coco/images/'
ann_root: 'annotation'
coco_gt_root: 'annotation/coco_gt'

# set pretrained as a file path or an url
pretrained: ''

batch_size: 32
init_lr: 1e-5

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5